version: '3'

services:
  orders-db:
    container_name: orders_database
    image: postgres:16.2
    restart: always
    volumes:
      # carpeta_local:carpeta_imagen
      - ./postgres:/var/lib/postgresql/data
    ports:
    # puerto_local:puerto_imagen
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=ordersdb
      